---
# specify tasks that should only be run when another task reports changed here:
#- name: a handler listening for a change
#  ansible.builtin.debug:
#    msg: i am a handler
#  listen: change # i am listening for "notify: change" statements

# since blocks are not supported in handlers the cleanest way to fire multiple tasks for the same handler is to use the following pattern.
# reference:
#   https://github.com/ansible/ansible/issues/14270
#   https://github.com/ansible/ansible/issues/42353
#- name: i fire multiple tasks
#  ansible.builtin.include_tasks: example_handler.yml
#  listen: example handler